### ISSUE TITLE
RGBカメラで得られる画像(サイズ等)が不明

### ISSUE THREAD

**Issue by clucker357** [ry0hei-kobayashi/tam_ros_lecture-group4#1]
標識認識の中身(RGBの画素値の比較とエッジ検出)は出来たが入力のサイズや画質が分からないため入力直後の変換(画質を入力からどの程度下げて良いか)が決定できないため作業の完了が出来ないです。

**Comment by ry0hei-kobayashi** [comment]
承知しました．報告ありがとうございます．カメラにはrealsense D415を用います．入力サイズはRGBが1280x720だったと思います．
詳細は以下より確認できます．https://www.intelrealsense.com/depth-camera-d415/ or
https://www.switch-science.com/products/3632
明日でよいので推定時にGPUメモリをどの程度消費するかの情報が欲しいです．よろしくお願いします．

2024年5月29日(水) 17:50 clucker357 ***@***.***>:

**Comment by clucker357** [comment]
現状だと、RGBの値の比率の計算とエッジ検出しかしていない(それで識別できる)ためGPUは要らないです。

深度も計測できるカメラであると今、把握しました。
